In [ ]:
import mod1

print(mod1.add(3,5))

In [ ]:
print(mod1.sub(5, 3))

In [ ]:
from mod1 import add
add(5, 4)

In [ ]:
# 하위 폴더에 module이 존재하는 경우 
# from 폴더명 import 모듈명
from modules import mod2

print(mod2.area(3))

In [ ]:
import mod3

a = mod3.Class_1(3, 4)
print(a.add())

In [ ]:
import pandas as pd

class change_dt():
    def regist_pandas(self, input_url):
        self.dt = pd.read_csv(input_url)
        return self.dt
    
    def nan_count(self):
        return self.dt.isna().sum()
    
    def dt_sort(self, input_value, input_inplce = False):
        return self.dt.sort_values(input_value, inplace=input_inplce)
    
    def dt_drop(self, input_columns = [], input_inplace = False):
        return self.dt.drop(input_columns, axis=1, inplace= input_inplace)
    
    def dt_change_c(self, input_columns):
        self.dt.columns = input_columns
        return True

a = change_dt()
dt = a.regist_pandas("./csv/Sales Records.csv")
a.nan_count()
a.dt_sort("Country", True)
a.dt_drop(["Ship Date", "Order ID", "Sales Channel", "Total Revenue"], True)
a.dt_change_c(["지역", "국가", "상품타입", "배송순위", 
                    "주문날짜", "판매개수", "단가", "원가", 
                    "총비용", "총이윤"])

In [ ]:
a.dt

In [26]:
from modules import change_pandas as cp

a = cp.change_dt()

In [27]:
dt = a.regist_pandas("./csv/Sales Records.csv")

In [28]:
a.nan_count()
a.dt_sort("Country", True)
a.dt_drop(["Ship Date", "Order ID", "Sales Channel", "Total Revenue"], True)
a.dt_change_c(["지역", "국가", "상품타입", "배송순위", 
                    "주문날짜", "판매개수", "단가", "원가", 
                    "총비용", "총이윤"])

True

In [29]:
a.dt

,지역,국가,상품타입,배송순위,주문날짜,판매개수,단가,원가,총비용,총이윤
4027,Middle East and North Africa,Afghanistan,Cereal,H,7/24/2013,9402,205.70,117.11,1101068.22,832923.18
3482,Middle East and North Africa,Afghanistan,Household,L,2/4/2012,1391,668.27,502.54,699033.14,230530.43
7775,Middle East and North Africa,Afghanistan,Cereal,H,8/20/2015,7300,205.70,117.11,854903.00,646707.00
5976,Middle East and North Africa,Afghanistan,Meat,H,8/11/2012,5075,421.89,364.69,1850801.75,290290.00
400,Middle East and North Africa,Afghanistan,Household,M,3/25/2011,92,668.27,502.54,46233.68,15247.16
...,...,...,...,...,...,...,...,...,...,...
4288,Sub-Saharan Africa,Zimbabwe,Cereal,C,1/16/2016,3867,205.70,117.11,452864.37,342577.53
5432,Sub-Saharan Africa,Zimbabwe,Office Supplies,L,1/26/2010,2073,651.21,524.96,1088242.08,261716.25
9541,Sub-Saharan Africa,Zimbabwe,Fruits,C,11/20/2015,5904,9.33,6.92,40855.68,14228.64
7640,Sub-Saharan Africa,Zimbabwe,Clothes,C,1/21/2017,3467,109.28,35.84,124257.28,254616.48
8080,Sub-Saharan Africa,Zimbabwe,Fruits,C,12/29/2012,9640,9.33,6.92,66708.80,23232.40